services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password # Senha do usuário root
      - MYSQL_DATABASE=timesheet # Nome do banco de dados
      - MYSQL_USER=timesheet_user # Nome do usuário
      - MYSQL_PASSWORD=timesheet_password # Senha do usuário
      - TZ=America/Sao_Paulo # Defina o fuso horário local
    ports:
      - '3306:3306' # Porta para o banco de dados MariaDB
    volumes:
      - ./data:/var/lib/mysql # Persistência dos dados
    networks:
      - db-network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb # Conecta automaticamente ao serviço do MariaDB
      - TZ=America/Sao_Paulo # Fuso horário
    ports:
      - '8082:8080' # Porta para acessar o Adminer
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge
