services:
  postgres-workbench:
    image: dpage/pgadmin4:latest
    container_name: postgres-workbench
    env_file:
      - .env # Variáveis de ambiente externas
    environment:
      - PGADMIN_DEFAULT_EMAIL=samuelfamilia@gmail.com # Email padrão para login no pgAdmin
      - PGADMIN_DEFAULT_PASSWORD=admin
      - TZ=America/Sao_Paulo # Fuso horário local
    ports:
      - '5059:80' # Porta para acessar o pgAdmin no navegador
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin # Persistência de dados do Workbench
    networks:
      - time-sheet-network
    restart: unless-stopped

  postgres-database:
    image: postgres:latest
    container_name: postgres-database
    env_file:
      - .env # Variáveis de ambiente externas
    environment:
      - TZ=America/Sao_Paulo # Fuso horário local
    ports:
      - '5432:5432' # Porta padrão do PostgreSQL
    volumes:
      - ./pgdata:/var/lib/postgresql/data # Persistência de dados do banco
    networks:
      - time-sheet-network
    restart: unless-stopped

#
#  # Spring Boot Application
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: time-sheet-spring
#    container_name: spring-time-sheet
#    command: mvn test
#
#    env_file:
#      - .env
#
#    ports:
#      - "9090:8080"
#    volumes:
#      - ./logs:/logs
#    networks:
#      - time-sheet-network

networks:
 time-sheet-network:
   driver: bridge
